apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: webtest
  namespace: webtest-istio-flagger
spec:
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webtest
  # the maximum time in seconds for the canary deployment
  # to make progress before it is rollback (default 600s)
  progressDeadlineSeconds: 60
  autoscalerRef:
    apiVersion: autoscaling/v2beta2
    kind: HorizontalPodAutoscaler
    name: webtest
  service:
    # service port number
    port: 8080
    # container port number or name (optional)
    targetPort: 8080
    # istio gateways (optional)
    gateways:
    - webtest
    # istio virtual service host names (optional)
    hosts:
    - "webtest-istio-flagger.playground.ordergroove.com"
    # istio traffic policy (optional)
    trafficPolicy:
      tls:
        # use istio_MUTUAL when mTLS is enabled
        mode: DISABLE
    # istio retry policy (optional)
    retries:
      attempts: 3
      perTryTimeout: 1s
      retryOn: "gateway-error,connect-failure,refused-stream"
  analysis:
    # schedule interval (default 60s)
    interval: 1m
    # max number of failed metric checks before rollback
    threshold: 5
    # max traffic percentage routed to canary
    # percentage (0-100)
    maxWeight: 50
    # canary increment step
    # percentage (0-100)
    stepWeight: 10
    metrics:
    - name: request-success-rate
      # minimum req success rate (non 5xx responses)
      # percentage (0-100)
      thresholdRange:
        min: 99
      interval: 1m
    - name: request-duration
      # maximum req duration P99
      # milliseconds
      thresholdRange:
        max: 500
      interval: 30s
    # testing (optional)
    webhooks:
      - name: acceptance-test
        type: pre-rollout
        url: http://flagger-loadtester.webtest-istio-flagger/
        timeout: 30s
        metadata:
          type: bash
          cmd: "curl -s http://webtest-canary.webtest-istio-flagger:8080 | grep Canary"
      - name: load-test
        url: http://flagger-loadtester.webtest-istio-flagger/
        timeout: 5s
        metadata:
          cmd: "hey -z 1m -q 10 -c 2 http://webtest-canary.webtest-istio-flagger:8080/"
