apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webtest
  name: webtest-classic
  namespace: webtest-classic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webtest
  template:
    metadata:
      labels:
        app: webtest
    spec:
      containers:
      - image: gcr.io/ogplayground/webtest:v15
        imagePullPolicy: IfNotPresent
        name: webtest
        ports:
        - containerPort: 8080
      serviceAccountName: webtest-service-account
      terminationGracePeriodSeconds: 0
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webtest-service-account
  namespace: webtest-classic
